"""``llmtrainer evaluate``: base vs specialist on the held-out (test-split-only) items, via the existing evalsuite.

Backends:
* ``stub``: deterministic toy subjects, offline. Plumbing only; the resulting EvaluationRun uses a stub evaluator and can
  never allow an improvement claim.
* ``hf``: real generation with transformers (+peft). Dry-run by default (prints the plan); ``execute=True`` loads local
  weights (never downloads unless ``allow_download``).
"""

from __future__ import annotations

import json
import shlex
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable

from .. import pipeline as pl
from ..clock import today
from ..datasets import load_split
from ..evalsuite import CallableSubject, LexicalRetriever, build_items, check_leakage, load_test_chunks, run_suite, to_evaluation_run
from ..evalsuite.harness import SuiteResult
from ..hashing import hash_obj, short
from ..pipeline import WorkspaceError
from ..schemas import DatasetManifest, EvaluationRun, EvaluatorInfo, TrainingRun
from . import hf_backend
from .importer import read_job_state
from .verify import chunk_table, load_heldout, verify_workspace_dataset

STUB_EVALUATOR = EvaluatorInfo(name="evalsuite_heuristic_stub_subjects", version="1", is_stub=True)
STUB_NOTE = ("STUB BACKEND: the subjects are deterministic toy responders, not models. These numbers exercise the pipeline only and "
             "make no statement about any model; improvement_claim_allowed is forced to false.")


def list_runs(ws: pl.Workspace) -> list[TrainingRun]:
    out = []
    for f in sorted((ws.root / "runs").glob("*/training_run.json")):
        out.append(TrainingRun.model_validate_json(f.read_text(encoding="utf-8")))
    return out


def latest_run(ws: pl.Workspace, dataset: DatasetManifest | None = None, run_id: str | None = None) -> TrainingRun | None:
    runs = list_runs(ws)
    if run_id is not None:
        for r in runs:
            if r.run_id == run_id:
                return r
        raise WorkspaceError(f"training run {run_id} not found in {ws.root / 'runs'}")
    runs = [r for r in runs if r.status == "completed" and not r.is_pipeline_validation_stub
            and (dataset is None or r.dataset_hash == dataset.content_hash)]
    return max(runs, key=lambda r: (r.finished_on or "", r.run_id)) if runs else None


@dataclass
class EvalOutcome:
    executed: bool
    backend: str
    plan: dict
    evalrun: EvaluationRun | None = None
    path: Path | None = None
    sidecar: dict = field(default_factory=dict)

    def as_dict(self) -> dict:
        d = {"executed": self.executed, "backend": self.backend, **self.plan}
        if self.evalrun is not None:
            d |= {"eval_id": self.evalrun.eval_id, "evaluation_hash": self.evalrun.content_hash,
                  "is_stub": self.evalrun.evaluator.is_stub, "improvement_claim_allowed": self.evalrun.improvement_claim_allowed,
                  "path": str(self.path), "comparisons": [c.model_dump() for c in self.evalrun.comparisons]}
        return d


def _stub_subjects() -> list[CallableSubject]:
    """Deterministic toy responders. Base never knows; the 'specialist' parrots the first provided source sentence."""
    def base(prompt: str) -> str:
        return "I do not know."

    def specialist(prompt: str) -> str:
        if "Sources:" in prompt:
            for ln in prompt.split("Sources:", 1)[1].splitlines():
                if ln.startswith("[") and "]" in ln:
                    ref, text = ln[1:].split("]", 1)
                    return f"{text.strip()} [{ref}]"
            return "I do not know."
        return "tighten the housing bolt using the calibrated wrench"

    return [CallableSubject("base", "stub-base", base), CallableSubject("specialist", "stub-specialist", specialist)]


def _stub_clock():
    t = {"v": 0.0}

    def clock() -> float:
        t["v"] += 0.001
        return t["v"]

    return clock


def _items(ws: pl.Workspace, dataset: DatasetManifest, train_val_rows: list[dict]):
    imported = load_heldout(ws)
    if imported:
        return imported, "imported (eval/heldout.jsonl from the job, re-verified)"
    chunks = load_test_chunks(dataset, ws.root / "corpus", ws.sources())
    items = build_items(chunks, domain=ws.project().domain)
    if not items:
        raise WorkspaceError("no held-out evaluation items could be derived from the test split")
    check_leakage(items, dataset, train_val_rows)
    return items, "regenerated by the desktop from test-split chunks"


def _retriever(ws: pl.Workspace) -> LexicalRetriever:
    chunks = [{"ref": f"{sid}/{cid}", "text": c["text"]} for (sid, cid), c in sorted(chunk_table(ws).items()) if c["role"] != "excluded"]
    return LexicalRetriever(chunks)


def _group_overlap(dataset: DatasetManifest) -> int:
    g: dict[str, set[str]] = {s: set() for s in ("train", "validation", "test")}
    for e in dataset.examples:
        g[e.split].add(e.group_id)
    return len(g["test"] & (g["train"] | g["validation"])) + len(g["train"] & g["validation"])


def _command(ws: pl.Workspace, backend: str, run_id, base_path, adapter_path, allow_download) -> str:
    parts = ["llmtrainer", "evaluate", shlex.quote(str(ws.root)), "--backend", backend, "--execute"]
    for flag, v in (("--run", run_id), ("--base-model-path", base_path), ("--adapter-path", adapter_path)):
        if v:
            parts += [flag, shlex.quote(str(v))]
    if allow_download:
        parts.append("--allow-download")
    return " ".join(parts)


def evaluate_workspace(
    ws: pl.Workspace, *, backend: str = "stub", run_id: str | None = None, execute: bool = False, allow_download: bool = False,
    base_model_path: str | None = None, adapter_path: str | None = None, base_model_id: str | None = None, seed: int = 0,
    generators: tuple[Callable[[str], str], Callable[[str], str]] | None = None,
) -> EvalOutcome:
    """Evaluate on the held-out items. ``generators`` (base, specialist) is an injection point for tests/other runtimes."""
    if backend not in ("stub", "hf"):
        raise ValueError(f"unknown backend {backend!r}")
    dataset = pl.latest_dataset(ws)
    problems = verify_workspace_dataset(ws, dataset)
    if problems:
        raise WorkspaceError("dataset verification failed, refusing to evaluate:\n  " + "\n  ".join(problems))
    ds_root = ws.root / "datasets"
    train_val = load_split(ds_root, dataset, "train") + load_split(ds_root, dataset, "validation")
    items, heldout_source = _items(ws, dataset, train_val)
    state = read_job_state(ws.root) or {}
    run = latest_run(ws, dataset, run_id) if backend == "hf" or run_id else None
    base_id = base_model_id or (run.base_model_id if run else None) or (state.get("base_model") or {}).get("registry_id") or "unknown-base"
    plan: dict = {
        "mode": "execute" if (execute or backend == "stub") else "dry-run (nothing loaded, nothing downloaded, nothing evaluated)",
        "held_out_items": len(items), "item_kinds": {k: sum(1 for i in items if i.kind == k) for k in ("fact", "concept")},
        "heldout_source": heldout_source, "split_read": "test (evaluation only)", "dataset_id": dataset.dataset_id,
        "dataset_hash": dataset.content_hash,
    }

    if backend == "stub":
        subjects = _stub_subjects()
        clock = _stub_clock()
        stub = True
    else:
        base_path = base_model_path or (run.hyperparameters.get("base_model_path") if run else None)
        adapter = adapter_path or (str(ws.root / "runs" / run.run_id / "output" / "adapter") if run else None)
        adapter_hash = (run.output_artifacts.get("adapter/adapter_model.safetensors") if run else None)
        spec_ref = f"{base_id}+adapter:{run.run_id}" if run else f"{base_id}+adapter:{Path(adapter).name}" if adapter else f"{base_id}+adapter:none"
        plan |= {
            "subjects": {"base": base_id, "specialist": spec_ref}, "base_model_path": base_path, "adapter_path": adapter,
            "training_run": run.run_id if run else None,
            "adapter_present": bool(adapter and Path(adapter).is_dir()),
            "missing_dependencies": hf_backend.missing_dependencies(True) if generators is None else [],
            "download_allowed": allow_download,
            "would_download": bool(base_path) and not Path(base_path).is_dir(),
            "reproducible_command": _command(ws, "hf", run.run_id if run else run_id, base_path, adapter_path, allow_download),
        }
        if not (execute or generators is not None):
            if not run and not adapter_path:
                plan["warnings"] = ["no completed training run and no --adapter-path: nothing to evaluate as 'specialist' yet"]
            return EvalOutcome(False, backend, plan)
        if generators is None:
            if not base_path:
                raise WorkspaceError("hf evaluation needs --base-model-path (or a training run that records it)")
            if not adapter:
                raise WorkspaceError("hf evaluation needs a trained adapter: pass --run RUN_ID or --adapter-path")
            if not Path(base_path).is_dir() and not allow_download:
                raise WorkspaceError(f"base model path {base_path!r} is not a local directory; pass --allow-download to permit a download")
            pair = hf_backend.HFPair(base_path, adapter, allow_download=allow_download)
            generators = (pair.base, pair.specialist)
        subjects = [CallableSubject("base", base_id, generators[0]),
                    CallableSubject("specialist", spec_ref, generators[1], artifact_hash=adapter_hash)]
        import time
        clock = time.perf_counter
        stub = False

    suite: SuiteResult = run_suite(subjects, items, retrieve=_retriever(ws), seed=seed, clock=clock)
    synthetic = any(i.synthetic for i in items)
    evalrun = to_evaluation_run(suite, project_id=ws.project().project_id, dataset=dataset,
                                train_eval_group_overlap=_group_overlap(dataset), evaluated_on=today(), subjects=subjects, synthetic=synthetic)
    if stub:
        d = evalrun.model_dump(mode="json", exclude={"content_hash"})
        d["evaluator"] = STUB_EVALUATOR.model_dump()
        d["improvement_claim_allowed"] = False
        d["notes"] = [STUB_NOTE, *d["notes"]]
        d["eval_id"] = "eval-" + short(hash_obj([d["eval_id"], "stub"]))
        evalrun = EvaluationRun.model_validate(d).seal()
    sidecar = {
        "eval_id": evalrun.eval_id, "backend": backend, "stub": stub, "heldout_source": heldout_source, "synthetic_data": synthetic,
        "delta_ci": {m: list(ci) for m, ci in suite.delta_ci.items()},
        "metric_n": {r.metric: r.n for r in evalrun.metrics if r.subject_role == "specialist"},
        "performance": {role: rep.performance() for role, rep in suite.reports.items()},
        "items": {"total": len(items), "fact": plan["item_kinds"]["fact"], "concept": plan["item_kinds"]["concept"]},
        "subject_models": {s.role: s.ref for s in subjects}, "training_run_id": run.run_id if run else None,
        "caveats": suite.caveats, "used_retrieval": suite.used_retrieval,
    }
    evals = ws.root / "evals"
    evals.mkdir(exist_ok=True)
    path = evals / f"{evalrun.eval_id}.json"
    if path.exists() and json.loads(path.read_text(encoding="utf-8")).get("content_hash") != evalrun.content_hash:
        raise WorkspaceError(f"{path} exists with different content; evaluation artifacts are never silently overwritten")
    path.write_text(evalrun.to_json(), encoding="utf-8")
    (evals / f"{evalrun.eval_id}.report.json").write_text(json.dumps(sidecar, indent=2, sort_keys=True), encoding="utf-8")
    return EvalOutcome(True, backend, plan, evalrun, path, sidecar)
