import groovy.json.JsonOutput
import groovy.json.JsonSlurper

plugins { id("org.jetbrains.kotlin.jvm") }

// Pure-JVM module bundled (dexed) into the OTA product bundle. Runtime deps: kotlin-stdlib (host-provided) and the
// Android platform's own org.json ONLY. Anything else must be pure Java/Kotlin and dexed in too (avoid).
kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
        freeCompilerArgs.addAll("-Xstring-concat=inline", "-Xlambdas=class", "-Xsam-conversions=class")
    }
}
java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

// ---- Embedded model catalog, generated at BUILD time from registry/base-models/*.json -------------------------------
// The JSON is emitted as Kotlin string pieces (each far below the 65535-byte class-file constant limit; non-ASCII is
// \u-escaped) that are joined at runtime, so JVM tests and the Android dex both load the identical registry.
val registryDir = rootProject.layout.projectDirectory.dir("registry/base-models")
val generatedRegistryDir = layout.buildDirectory.dir("generated/registry/kotlin")

val generateEmbeddedRegistry by tasks.registering {
    inputs.dir(registryDir)
    outputs.dir(generatedRegistryDir)
    doLast {
        fun esc(s: String): String {
            val sb = StringBuilder()
            for (c in s) when {
                c == '\\' -> sb.append("\\\\")
                c == '"' -> sb.append("\\\"")
                c == '$' -> sb.append("\\$")
                c == '\n' -> sb.append("\\n")
                c == '\r' -> sb.append("\\r")
                c == '\t' -> sb.append("\\t")
                c.code < 0x20 || c.code > 0x7e -> sb.append("\\u").append(String.format("%04x", c.code))
                else -> sb.append(c)
            }
            return sb.toString()
        }
        val files = registryDir.asFile.listFiles { f -> f.isFile && f.name.endsWith(".json") }!!.sortedBy { it.name }
        val out = StringBuilder()
        out.append("// GENERATED by :studio-core:generateEmbeddedRegistry from registry/base-models/*.json. Do not edit.\n")
        out.append("package com.hotatticgames.llmtrainer.studio.core\n\n")
        out.append("object EmbeddedRegistry {\n")
        out.append("    /** (file name, registry entry JSON) in file-name order. */\n")
        out.append("    val files: List<Pair<String, String>> = listOf(\n")
        for (f in files) {
            val parsed = JsonSlurper().parseText(f.readText(Charsets.UTF_8))
            val min = JsonOutput.toJson(parsed)
            val pieces = min.chunked(6000)
            out.append("        \"${esc(f.name)}\" to listOf(\n")
            for (p in pieces) out.append("            \"${esc(p)}\",\n")
            out.append("        ).joinToString(\"\"),\n")
        }
        out.append("    )\n}\n")
        val dir = generatedRegistryDir.get().asFile
        dir.mkdirs()
        File(dir, "EmbeddedRegistry.kt").writeText(out.toString(), Charsets.UTF_8)
    }
}

kotlin.sourceSets.named("main") {
    kotlin.srcDir(generateEmbeddedRegistry.map { generatedRegistryDir.get().asFile })
}

dependencies {
    compileOnly("org.json:json:20231013")          // on Android the platform provides org.json at runtime
    testImplementation("org.json:json:20231013")   // JVM tests need a real implementation
    testImplementation(kotlin("test"))
    api(project(":studio-api"))
    implementation(project(":extract"))
    implementation(project(":qualify"))
}

tasks.jar {
    archiveBaseName.set("studio-core")
    archiveVersion.set("")
}

tasks.test {
    useJUnit()
    systemProperty("repo.root", rootProject.projectDir.path)
    systemProperty("sample.dir", layout.buildDirectory.dir("sample").get().asFile.path)
    maxHeapSize = "1g"
}
